package view;

import model.*;

import javax.swing.*;
import java.awt.*;

/**
 * Class RevenueView represents the amount of revenue generated by individual sources. 
 *
 * @author Thomas Lambregts
 * @version 1.0 (12-04-2016)
 */

public class RevenueView extends AbstractView {

    private Dimension size;

    private JLabel title;
    private JLabel normalCarRevenue;
    private JLabel memberCarRevenue;
    private JLabel combinedTotalRevenue;
    
    private JLabel elapsedTime; 
   
    private JLabel carsInfoEnter;
    private JLabel carsInfoPay;
    private JLabel carsInfoExit;
    
    private double numberOfNormalCars;
    private double numberOfMemberCars;
    private double numberOfCombinedRevenue; 
    private String time; 
    

    /**
     * Constructor creates an instance of the RevenueView.
     * It stores its data to the given model.
     *
     * @param model The model that applies to this view
     */
    public RevenueView(CarParkLogic model) {
        super(model);

        this.size = new Dimension(100, 100);

        title = new JLabel("Live revenue information:");
        title.setFont(new Font("SansSerif", Font.BOLD, 14));
        
        normalCarRevenue = new JLabel("");
        memberCarRevenue = new JLabel("");
        combinedTotalRevenue = new JLabel("");
        elapsedTime = new JLabel("");
        
        carsInfoEnter = new JLabel("");
        carsInfoPay = new JLabel("");
        carsInfoExit  = new JLabel("");
       

		this.setLayout(null);
        add(title);
        add(normalCarRevenue);
        add(memberCarRevenue);
        add(combinedTotalRevenue);
        add(elapsedTime);
      
        
        title.setBounds(0, 5, 220, 20);
        normalCarRevenue.setBounds(0, 55, 400, 20);
        memberCarRevenue.setBounds(0, 75, 400, 20);
        combinedTotalRevenue.setBounds(0, 95, 400, 20);
        elapsedTime.setBounds(0, 115, 400, 20);
       
    }

    /**
     * Get's called by the super model class when something needs to be updated
     */
    public void updateView(){

        CarParkLogic carPark = (CarParkLogic) super.model;

        numberOfNormalCars = carPark.getRevenueNormal(); 
        numberOfMemberCars = carPark.getRevenueMembers(); 
        numberOfCombinedRevenue = carPark.getRevenueTotal();
        time = carPark.getTime();

        normalCarRevenue.setText("Revenue from normal customers: " + "€" +  numberOfNormalCars);
        memberCarRevenue.setText("Revenue from members: " + "€" + numberOfMemberCars);
        combinedTotalRevenue.setText("Total revenue:" + "€" + numberOfCombinedRevenue);
        elapsedTime.setText(time);
        ;

        setVisible(true);
        super.updateView();
    }
}